
package ru.gismeteo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegisterSoap", targetNamespace = "http://ws.gismeteo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegisterSoap {


    /**
     * 
     * @param email
     * @param name
     * @param deviceid
     * @return
     *     returns ru.gismeteo.ws.RegisterResult
     */
    @WebMethod(operationName = "RegisterHHUser", action = "http://ws.gismeteo.ru/RegisterHHUser")
    @WebResult(name = "RegisterHHUserResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "RegisterHHUser", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.RegisterHHUser")
    @ResponseWrapper(localName = "RegisterHHUserResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.RegisterHHUserResponse")
    public RegisterResult registerHHUser(
        @WebParam(name = "name", targetNamespace = "http://ws.gismeteo.ru/")
        String name,
        @WebParam(name = "email", targetNamespace = "http://ws.gismeteo.ru/")
        String email,
        @WebParam(name = "deviceid", targetNamespace = "http://ws.gismeteo.ru/")
        String deviceid);

    /**
     * 
     * @param email
     * @param name
     * @param deviceid
     * @return
     *     returns ru.gismeteo.ws.RegisterResult
     */
    @WebMethod(operationName = "RegisterMMUser", action = "http://ws.gismeteo.ru/RegisterMMUser")
    @WebResult(name = "RegisterMMUserResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "RegisterMMUser", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.RegisterMMUser")
    @ResponseWrapper(localName = "RegisterMMUserResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.RegisterMMUserResponse")
    public RegisterResult registerMMUser(
        @WebParam(name = "name", targetNamespace = "http://ws.gismeteo.ru/")
        String name,
        @WebParam(name = "email", targetNamespace = "http://ws.gismeteo.ru/")
        String email,
        @WebParam(name = "deviceid", targetNamespace = "http://ws.gismeteo.ru/")
        String deviceid);

}
