
package ru.gismeteo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Register", targetNamespace = "http://ws.gismeteo.ru/", wsdlLocation = "http://ws.gismeteo.ru/Registration/Register.asmx?WSDL")
public class Register
    extends Service
{

    private final static URL REGISTER_WSDL_LOCATION;
    private final static WebServiceException REGISTER_EXCEPTION;
    private final static QName REGISTER_QNAME = new QName("http://ws.gismeteo.ru/", "Register");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.gismeteo.ru/Registration/Register.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTER_WSDL_LOCATION = url;
        REGISTER_EXCEPTION = e;
    }

    public Register() {
        super(__getWsdlLocation(), REGISTER_QNAME);
    }

    public Register(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTER_QNAME, features);
    }

    public Register(URL wsdlLocation) {
        super(wsdlLocation, REGISTER_QNAME);
    }

    public Register(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTER_QNAME, features);
    }

    public Register(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Register(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegisterSoap
     */
    @WebEndpoint(name = "RegisterSoap")
    public RegisterSoap getRegisterSoap() {
        return super.getPort(new QName("http://ws.gismeteo.ru/", "RegisterSoap"), RegisterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterSoap
     */
    @WebEndpoint(name = "RegisterSoap")
    public RegisterSoap getRegisterSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.gismeteo.ru/", "RegisterSoap"), RegisterSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTER_EXCEPTION!= null) {
            throw REGISTER_EXCEPTION;
        }
        return REGISTER_WSDL_LOCATION;
    }

}
