
package ru.gismeteo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherSoap", targetNamespace = "http://ws.gismeteo.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherSoap {


    /**
     * 
     * @param location
     * @param serial
     * @return
     *     returns ru.gismeteo.ws.HHObservationResult
     */
    @WebMethod(operationName = "GetHHObservation", action = "http://ws.gismeteo.ru/GetHHObservation")
    @WebResult(name = "GetHHObservationResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetHHObservation", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetHHObservation")
    @ResponseWrapper(localName = "GetHHObservationResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetHHObservationResponse")
    public HHObservationResult getHHObservation(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "location", targetNamespace = "http://ws.gismeteo.ru/")
        int location);

    /**
     * 
     * @param location
     * @param serial
     * @return
     *     returns ru.gismeteo.ws.HHForecastResult
     */
    @WebMethod(operationName = "GetHHForecast", action = "http://ws.gismeteo.ru/GetHHForecast")
    @WebResult(name = "GetHHForecastResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetHHForecast", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetHHForecast")
    @ResponseWrapper(localName = "GetHHForecastResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetHHForecastResponse")
    public HHForecastResult getHHForecast(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "location", targetNamespace = "http://ws.gismeteo.ru/")
        int location);

    /**
     * 
     * @param dt
     * @param location
     * @param serial
     * @return
     *     returns ru.gismeteo.ws.GetLocalTimeOffsetResult
     */
    @WebMethod(operationName = "GetLocalTimeOffset", action = "http://ws.gismeteo.ru/GetLocalTimeOffset")
    @WebResult(name = "GetLocalTimeOffsetResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetLocalTimeOffset", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetLocalTimeOffset")
    @ResponseWrapper(localName = "GetLocalTimeOffsetResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetLocalTimeOffsetResponse")
    public GetLocalTimeOffsetResult getLocalTimeOffset(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "location", targetNamespace = "http://ws.gismeteo.ru/")
        int location,
        @WebParam(name = "dt", targetNamespace = "http://ws.gismeteo.ru/")
        XMLGregorianCalendar dt);

    /**
     * 
     * @param location
     * @param serial
     * @return
     *     returns ru.gismeteo.ws.GeoMagneticForecastResult
     */
    @WebMethod(operationName = "GetGeoMagneticForecast", action = "http://ws.gismeteo.ru/GetGeoMagneticForecast")
    @WebResult(name = "GetGeoMagneticForecastResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetGeoMagneticForecast", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetGeoMagneticForecast")
    @ResponseWrapper(localName = "GetGeoMagneticForecastResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetGeoMagneticForecastResponse")
    public GeoMagneticForecastResult getGeoMagneticForecast(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "location", targetNamespace = "http://ws.gismeteo.ru/")
        int location);

    /**
     * 
     * @param dt
     * @param serial
     * @return
     *     returns ru.gismeteo.ws.GetMoonInfoResult
     */
    @WebMethod(operationName = "GetMoonInfo", action = "http://ws.gismeteo.ru/GetMoonInfo")
    @WebResult(name = "GetMoonInfoResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetMoonInfo", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetMoonInfo")
    @ResponseWrapper(localName = "GetMoonInfoResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetMoonInfoResponse")
    public GetMoonInfoResult getMoonInfo(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "dt", targetNamespace = "http://ws.gismeteo.ru/")
        XMLGregorianCalendar dt);

    /**
     * 
     * @param date
     * @param serial
     * @param townID
     * @return
     *     returns ru.gismeteo.ws.GetSunInfoResult
     */
    @WebMethod(operationName = "GetSunInfo", action = "http://ws.gismeteo.ru/GetSunInfo")
    @WebResult(name = "GetSunInfoResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetSunInfo", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetSunInfo")
    @ResponseWrapper(localName = "GetSunInfoResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetSunInfoResponse")
    public GetSunInfoResult getSunInfo(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "townID", targetNamespace = "http://ws.gismeteo.ru/")
        int townID,
        @WebParam(name = "date", targetNamespace = "http://ws.gismeteo.ru/")
        XMLGregorianCalendar date);

    /**
     * 
     * @param location
     * @param serial
     * @return
     *     returns ru.gismeteo.ws.MMForecastResult
     */
    @WebMethod(operationName = "GetMMForecast", action = "http://ws.gismeteo.ru/GetMMForecast")
    @WebResult(name = "GetMMForecastResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetMMForecast", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetMMForecast")
    @ResponseWrapper(localName = "GetMMForecastResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetMMForecastResponse")
    public MMForecastResult getMMForecast(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "location", targetNamespace = "http://ws.gismeteo.ru/")
        int location);

    /**
     * 
     * @param location
     * @param serial
     * @return
     *     returns ru.gismeteo.ws.MMObservationResult
     */
    @WebMethod(operationName = "GetMMObservation", action = "http://ws.gismeteo.ru/GetMMObservation")
    @WebResult(name = "GetMMObservationResult", targetNamespace = "http://ws.gismeteo.ru/")
    @RequestWrapper(localName = "GetMMObservation", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetMMObservation")
    @ResponseWrapper(localName = "GetMMObservationResponse", targetNamespace = "http://ws.gismeteo.ru/", className = "ru.gismeteo.ws.GetMMObservationResponse")
    public MMObservationResult getMMObservation(
        @WebParam(name = "serial", targetNamespace = "http://ws.gismeteo.ru/")
        String serial,
        @WebParam(name = "location", targetNamespace = "http://ws.gismeteo.ru/")
        int location);

}
